image: node:15.2.0

stages:
  - build

cache:
  paths:
    - node-modules/

build-pages:
  stage: build
  script:
    - CI=false npm install
    - CI=false npm run build
  artifacts:
    paths:
      - public